// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proxy.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Heartbeat struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Heartbeat) Reset()         { *m = Heartbeat{} }
func (m *Heartbeat) String() string { return proto.CompactTextString(m) }
func (*Heartbeat) ProtoMessage()    {}
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{0}
}

func (m *Heartbeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Heartbeat.Unmarshal(m, b)
}
func (m *Heartbeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Heartbeat.Marshal(b, m, deterministic)
}
func (m *Heartbeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Heartbeat.Merge(m, src)
}
func (m *Heartbeat) XXX_Size() int {
	return xxx_messageInfo_Heartbeat.Size(m)
}
func (m *Heartbeat) XXX_DiscardUnknown() {
	xxx_messageInfo_Heartbeat.DiscardUnknown(m)
}

var xxx_messageInfo_Heartbeat proto.InternalMessageInfo

type Notify struct {
	Cmd                  *string  `protobuf:"bytes,1,req,name=cmd" json:"cmd,omitempty"`
	Homepage             *string  `protobuf:"bytes,2,req,name=homepage" json:"homepage,omitempty"`
	Branch               *string  `protobuf:"bytes,3,req,name=branch" json:"branch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Notify) Reset()         { *m = Notify{} }
func (m *Notify) String() string { return proto.CompactTextString(m) }
func (*Notify) ProtoMessage()    {}
func (*Notify) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{1}
}

func (m *Notify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Notify.Unmarshal(m, b)
}
func (m *Notify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Notify.Marshal(b, m, deterministic)
}
func (m *Notify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Notify.Merge(m, src)
}
func (m *Notify) XXX_Size() int {
	return xxx_messageInfo_Notify.Size(m)
}
func (m *Notify) XXX_DiscardUnknown() {
	xxx_messageInfo_Notify.DiscardUnknown(m)
}

var xxx_messageInfo_Notify proto.InternalMessageInfo

func (m *Notify) GetCmd() string {
	if m != nil && m.Cmd != nil {
		return *m.Cmd
	}
	return ""
}

func (m *Notify) GetHomepage() string {
	if m != nil && m.Homepage != nil {
		return *m.Homepage
	}
	return ""
}

func (m *Notify) GetBranch() string {
	if m != nil && m.Branch != nil {
		return *m.Branch
	}
	return ""
}

type NotifyResp struct {
	Name                 *string  `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Message              *string  `protobuf:"bytes,2,req,name=message" json:"message,omitempty"`
	Homepage             *string  `protobuf:"bytes,3,req,name=homepage" json:"homepage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyResp) Reset()         { *m = NotifyResp{} }
func (m *NotifyResp) String() string { return proto.CompactTextString(m) }
func (*NotifyResp) ProtoMessage()    {}
func (*NotifyResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{2}
}

func (m *NotifyResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyResp.Unmarshal(m, b)
}
func (m *NotifyResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyResp.Marshal(b, m, deterministic)
}
func (m *NotifyResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyResp.Merge(m, src)
}
func (m *NotifyResp) XXX_Size() int {
	return xxx_messageInfo_NotifyResp.Size(m)
}
func (m *NotifyResp) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyResp.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyResp proto.InternalMessageInfo

func (m *NotifyResp) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *NotifyResp) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func (m *NotifyResp) GetHomepage() string {
	if m != nil && m.Homepage != nil {
		return *m.Homepage
	}
	return ""
}

type Login struct {
	Name                 *string  `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Homepages            []string `protobuf:"bytes,2,rep,name=homepages" json:"homepages,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Login) Reset()         { *m = Login{} }
func (m *Login) String() string { return proto.CompactTextString(m) }
func (*Login) ProtoMessage()    {}
func (*Login) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{3}
}

func (m *Login) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Login.Unmarshal(m, b)
}
func (m *Login) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Login.Marshal(b, m, deterministic)
}
func (m *Login) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Login.Merge(m, src)
}
func (m *Login) XXX_Size() int {
	return xxx_messageInfo_Login.Size(m)
}
func (m *Login) XXX_DiscardUnknown() {
	xxx_messageInfo_Login.DiscardUnknown(m)
}

var xxx_messageInfo_Login proto.InternalMessageInfo

func (m *Login) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Login) GetHomepages() []string {
	if m != nil {
		return m.Homepages
	}
	return nil
}

type LoginResp struct {
	Ok                   *bool    `protobuf:"varint,1,req,name=ok" json:"ok,omitempty"`
	Msg                  *string  `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResp) Reset()         { *m = LoginResp{} }
func (m *LoginResp) String() string { return proto.CompactTextString(m) }
func (*LoginResp) ProtoMessage()    {}
func (*LoginResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{4}
}

func (m *LoginResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResp.Unmarshal(m, b)
}
func (m *LoginResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResp.Marshal(b, m, deterministic)
}
func (m *LoginResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResp.Merge(m, src)
}
func (m *LoginResp) XXX_Size() int {
	return xxx_messageInfo_LoginResp.Size(m)
}
func (m *LoginResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResp proto.InternalMessageInfo

func (m *LoginResp) GetOk() bool {
	if m != nil && m.Ok != nil {
		return *m.Ok
	}
	return false
}

func (m *LoginResp) GetMsg() string {
	if m != nil && m.Msg != nil {
		return *m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*Heartbeat)(nil), "protocol.heartbeat")
	proto.RegisterType((*Notify)(nil), "protocol.notify")
	proto.RegisterType((*NotifyResp)(nil), "protocol.notifyResp")
	proto.RegisterType((*Login)(nil), "protocol.login")
	proto.RegisterType((*LoginResp)(nil), "protocol.loginResp")
}

func init() { proto.RegisterFile("proxy.proto", fileDescriptor_700b50b08ed8dbaf) }

var fileDescriptor_700b50b08ed8dbaf = []byte{
	// 208 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8f, 0xb1, 0x4e, 0xc6, 0x20,
	0x14, 0x85, 0xf3, 0x83, 0xfe, 0x96, 0xdb, 0xc4, 0x18, 0x06, 0x43, 0x8c, 0x43, 0xc3, 0xd4, 0x45,
	0x77, 0x5f, 0xc2, 0x81, 0xc1, 0x9d, 0x56, 0xa4, 0x4d, 0x0b, 0x97, 0x00, 0x83, 0x7d, 0x7b, 0x53,
	0x6c, 0x6d, 0x9a, 0x38, 0x71, 0xcf, 0x85, 0xf3, 0x1d, 0x0e, 0xd4, 0x21, 0xe2, 0xf7, 0xf2, 0x1a,
	0x22, 0x66, 0xe4, 0x55, 0x39, 0x7a, 0x9c, 0x65, 0x0d, 0x6c, 0x30, 0x3a, 0xe6, 0xce, 0xe8, 0x2c,
	0xdf, 0xe1, 0xea, 0x31, 0x8f, 0x5f, 0x0b, 0x7f, 0x00, 0xda, 0xbb, 0x4f, 0x71, 0x69, 0x48, 0xcb,
	0xd4, 0x3a, 0xf2, 0x27, 0xa8, 0x06, 0x74, 0x26, 0x68, 0x6b, 0x04, 0x29, 0xeb, 0x3f, 0xcd, 0x1f,
	0xe1, 0xda, 0x45, 0xed, 0xfb, 0x41, 0xd0, 0x72, 0xb3, 0x29, 0xf9, 0x01, 0xf0, 0xcb, 0x53, 0x26,
	0x05, 0xce, 0xe1, 0xc6, 0x6b, 0x67, 0x36, 0x68, 0x99, 0xb9, 0x80, 0x3b, 0x67, 0x52, 0x3a, 0xa0,
	0xbb, 0x3c, 0xe5, 0xd1, 0x73, 0x9e, 0x7c, 0x83, 0xdb, 0x19, 0xed, 0xe8, 0xff, 0x45, 0x3e, 0x03,
	0xdb, 0x1f, 0x26, 0x41, 0x1a, 0xda, 0x32, 0x75, 0x2c, 0xe4, 0x0b, 0xb0, 0x62, 0x2d, 0x3f, 0xba,
	0x07, 0x82, 0x53, 0x31, 0x57, 0x8a, 0xe0, 0xb4, 0xb6, 0x76, 0xc9, 0x0a, 0xd2, 0x5c, 0xd6, 0xd6,
	0x2e, 0xd9, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x75, 0x8e, 0xe7, 0x4a, 0x36, 0x01, 0x00, 0x00,
}
