// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proxy.proto

package codec

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Heartbeat struct {
	Timestamp            *int64   `protobuf:"varint,1,req,name=timestamp" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Heartbeat) Reset()         { *m = Heartbeat{} }
func (m *Heartbeat) String() string { return proto.CompactTextString(m) }
func (*Heartbeat) ProtoMessage()    {}
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{0}
}

func (m *Heartbeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Heartbeat.Unmarshal(m, b)
}
func (m *Heartbeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Heartbeat.Marshal(b, m, deterministic)
}
func (m *Heartbeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Heartbeat.Merge(m, src)
}
func (m *Heartbeat) XXX_Size() int {
	return xxx_messageInfo_Heartbeat.Size(m)
}
func (m *Heartbeat) XXX_DiscardUnknown() {
	xxx_messageInfo_Heartbeat.DiscardUnknown(m)
}

var xxx_messageInfo_Heartbeat proto.InternalMessageInfo

func (m *Heartbeat) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

type Event struct {
	MsgType              *string  `protobuf:"bytes,1,req,name=msgType" json:"msgType,omitempty"`
	Homepage             *string  `protobuf:"bytes,2,req,name=homepage" json:"homepage,omitempty"`
	Branch               *string  `protobuf:"bytes,3,req,name=branch" json:"branch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{1}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetMsgType() string {
	if m != nil && m.MsgType != nil {
		return *m.MsgType
	}
	return ""
}

func (m *Event) GetHomepage() string {
	if m != nil && m.Homepage != nil {
		return *m.Homepage
	}
	return ""
}

func (m *Event) GetBranch() string {
	if m != nil && m.Branch != nil {
		return *m.Branch
	}
	return ""
}

type Login struct {
	Homepage             *string  `protobuf:"bytes,1,req,name=homepage" json:"homepage,omitempty"`
	Name                 *string  `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Login) Reset()         { *m = Login{} }
func (m *Login) String() string { return proto.CompactTextString(m) }
func (*Login) ProtoMessage()    {}
func (*Login) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{2}
}

func (m *Login) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Login.Unmarshal(m, b)
}
func (m *Login) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Login.Marshal(b, m, deterministic)
}
func (m *Login) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Login.Merge(m, src)
}
func (m *Login) XXX_Size() int {
	return xxx_messageInfo_Login.Size(m)
}
func (m *Login) XXX_DiscardUnknown() {
	xxx_messageInfo_Login.DiscardUnknown(m)
}

var xxx_messageInfo_Login proto.InternalMessageInfo

func (m *Login) GetHomepage() string {
	if m != nil && m.Homepage != nil {
		return *m.Homepage
	}
	return ""
}

func (m *Login) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Heartbeat)(nil), "codec.heartbeat")
	proto.RegisterType((*Event)(nil), "codec.Event")
	proto.RegisterType((*Login)(nil), "codec.login")
}

func init() { proto.RegisterFile("proxy.proto", fileDescriptor_700b50b08ed8dbaf) }

var fileDescriptor_700b50b08ed8dbaf = []byte{
	// 162 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8c, 0xb1, 0x0a, 0xc2, 0x40,
	0x0c, 0x40, 0x69, 0x6b, 0xd5, 0xc6, 0x2d, 0x83, 0x1c, 0xe2, 0x20, 0x9d, 0x74, 0x71, 0xf5, 0x0b,
	0xfc, 0x81, 0xa2, 0x1f, 0x90, 0xd6, 0xd0, 0x16, 0xbc, 0xcb, 0x71, 0x0d, 0x62, 0xff, 0x5e, 0x38,
	0xac, 0xa2, 0x5b, 0x5e, 0x5e, 0x5e, 0x60, 0xe5, 0x83, 0x3c, 0xc7, 0xa3, 0x0f, 0xa2, 0x82, 0x79,
	0x23, 0x37, 0x6e, 0xca, 0x03, 0x14, 0x1d, 0x53, 0xd0, 0x9a, 0x49, 0x71, 0x0b, 0x85, 0xf6, 0x96,
	0x07, 0x25, 0xeb, 0x4d, 0xb2, 0x4b, 0xf7, 0x59, 0xf5, 0x5d, 0x94, 0x57, 0xc8, 0xcf, 0x0f, 0x76,
	0x8a, 0x06, 0x16, 0x76, 0x68, 0x2f, 0xa3, 0xe7, 0x78, 0x54, 0x54, 0x13, 0xe2, 0x06, 0x96, 0x9d,
	0x58, 0xf6, 0xd4, 0xb2, 0x49, 0xa3, 0xfa, 0x30, 0xae, 0x61, 0x5e, 0x07, 0x72, 0x4d, 0x67, 0xb2,
	0x68, 0xde, 0x54, 0x9e, 0x20, 0xbf, 0x4b, 0xdb, 0xbb, 0x9f, 0x38, 0xf9, 0x8b, 0x11, 0x66, 0x8e,
	0xec, 0xf4, 0x34, 0xce, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5f, 0xd5, 0x7c, 0xfa, 0xcf, 0x00,
	0x00, 0x00,
}
